# Generated by Django 4.0.4 on 2023-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тестовое поле'),
        ),
    ]
