# Generated by Django 4.0.4 on 2023-04-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0002_user_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
    ]
