# Generated by Django 4.0.4 on 2023-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images.png', upload_to='avatar/', verbose_name='Фото профиля'),
        ),
    ]
